### ISSUE TITLE
Team Comtress 2

### ISSUE THREAD

**Issue by MikhailaTF** [agrastiOs/Ultimate-TF2-Visual-Fix-Pack#16]
Hey, loving the effort and dedication being put in here!
I saw that it is on your current planning to integrate this project with the community fix-up pack on the steam workshop, this made me wonder if it was also an idea to integrate this project with team comtress 2?
While I do believe they take a closer look at anything related to coding, I figure this would be a lovely addition to the goal of that project as well.

**Comment by agrastiOs** [comment]
Hey!
It is in the plan that I will be proposing a version of the pack tailored for TC2 after the pack is complete.

**Comment by MikhailaTF** [comment]
Alright, loving the sound of that!
If I may be so troublesome, I've also been considering suggesting Neodement's consistent kill icons pack (and perhaps it's unofficial updates) which cleans and streamlines almost all of the current kill icons as well as implementing new ones (which I believe requires some coding) and since it is more of a GUI thing I wasn't sure to suggest it here, over on team comtress 2 or neither.
If it is worth noting, I have also voiced a suggestion to integrate more parts of the community fix-up pack into team comtress and that pack also includes a mod from Neodement herself that adds few new kill icons for weapons/situations that previously had none (these don't seem to be part of the mod I mentioned above).

**Comment by agrastiOs** [comment]
Thank you for the info and your kind words, we might get the kill icons fix into part 2 for the pack.

**Comment by Shrinks99** [comment]
As per [TC2 issue 74](https://github.com/mastercomfig/team-comtress-2/issues/74#issuecomment-695026219) it seems they are specifically avoiding art-related fixes and focusing on code in order to manage the scope of the project.  As far as integration goes, both projects seem to be designed as drag-and-drop objective fixes and improvements.  I'm not _incredibly_ well versed with Source by any means but I'm not sure what further integration between the two projects is required other than trying not to step on eachother's toes when it comes to making changes so you don't have duplicate fixes... though that seems to have sorted itself out considering they are purposefully not focusing on art.

**Comment by agrastiOs** [comment]
@Shrinks99 @MikhailaTF The pack has now been added to Team Comtress 2. https://github.com/mastercomfig/team-comtress-2/releases

**Comment by agrastiOs** [comment]
@Shrinks99 Nothing much should change, TC2 will keep receiving updates from the pack, as long as the final release gets out and Valve accepts this pack to the vanilla.
