### ISSUE TITLE
Integration of parts of the ModdingTF2/ TIP Update Pack

### ISSUE THREAD

**Issue by Shrinks99** [agrastiOs/Ultimate-TF2-Visual-Fix-Pack#19]
There's a handful of visual fixes [catalogued in this repository](https://github.com/ModdingTF2/The-closest-thing-to-an-updated-version-of-TF2-TIP) that I would like to be considered for inclusion in this pack.  Standouts are the [Cut Throat Concierge Fire Texture Fix](https://gamebanana.com/skins/126426), [Better Buff Banner Phong](https://gamebanana.com/skins/133267) (somewhat subjective), the [Shotgun Shells Texture Fix](https://gamebanana.com/skins/127587), and the [Sentry's Rockets Texture Fix](https://gamebanana.com/skins/127318).

Other more drastic changes like the inclusion of the TF2 Texture Improvement project and the HD gibs textures (which are _technically_ fixes as lots of gibs right now just straight up use the wrong textures) are a lot more subjective and wouldn't fit in a drag and drop pack of fixes.  Don't worry about those, but they're present in that repo as well.

I also recognize that these are all changes made by other artists, I feel like if contacted they'd be happy to share them considering they're visual fixes, in any case this is a solid list of bugs to tackle :P

**Comment by agrastiOs** [comment]
Hey, thank you for the suggestions. We're going to check on the Cut Throat Concierge (and Doe-Boy as that was mentioned in the kid's comments) and fix the fire texture ourselves, thanks for pointing that one out!

The Buff Banner already has phong fixed in our pack, and it even got a phong mask in our fix. The shotgun shells texture is a good idea to fix , we will either fix it for the final release or do it for part 2 (to conserve texture changes). The Sentry Rockets Texture Fix seems like a good thing to import or that we make the fix ourselves, however, it is a very minute detail, so we will consider it for part 2.

By the way, the creator of that pack you're taking about actually had been working on merging our fixes to his project!

**Comment by kevinvanrijn** [comment]
The wip branch is what's been done as far as merging this repo into mine, but I never ended up finishing it. I was waiting for the next big TF2 update to start on it again and clean everything up for another release but that's been taking longer than expected.

Everything in my repo is very subjective, and most of the changes from the community are included on a good faith basis, so I don't think anything should be copied over wholesale.

I believe pretty much everything has already been mentioned that might warrant another look from this repo. The one last thing I can think of is looking into the paint areas of the items included from Gabrielwoj. Most of them are still very subjective and take some creative liberties with the items (color changes mostly), but I remember distinctly that there were also some simple "paint area doesn't line up right" fixes that you might be interested in recreating if you're willing to wade through it all.

**Comment by agrastiOs** [comment]
Closing for now as per previous comment.
