### ISSUE TITLE
Casual mode

### ISSUE THREAD

**Issue by IgorExreme** [agrastiOs/Ultimate-TF2-Visual-Fix-Pack#40]
When i enter in a match on casual mode the game crashes.
Why this is happening?

**Comment by N-cognito** [comment]
Without a log it is hard to determine what caused the crash, but it's likely because this pack is not intended for Casual. All of Valve's servers run using SV_Pure 1, which forces the game to load the default files on the fly. This causes issues with mods, and when the game can't properly load the default files over the modded ones, the game can glitch out or outright crash.

**Comment by agrastiOs** [comment]
Closing as it is unfixable (only Valve could fix the sv_pure system to not be as clunky), as N-Cognito has well put.
