### ISSUE TITLE
Viewmodel animation snap command fix

### ISSUE THREAD

**Issue by unsubtract** [agrastiOs/Ultimate-TF2-Visual-Fix-Pack#66]
The August 11th, 2022 patch added a fix for some viewmodels using blended animations instead of snapped ones.
This does not work however if the TF2 Ultimate Visual Fix Pack is installed, probably due to the model files being changed.

**Comment by Whurrhurr** [comment]
can't figure out what you're talking about, installed the visual fix from the most recent commit of the visual fix and i tried quickly switching between weapons as pyro and medic and the viewmodels worked properly

**Comment by unsubtract** [comment]
> can't figure out what you're talking about, installed the visual fix from the most recent commit of the visual fix and i tried quickly switching between weapons as pyro and medic and the viewmodels worked properly

The behavior with the pack installed resembles how the animations worked prior to the update. They now differ from live TF2.

**Comment by unsubtract** [comment]
accidentally closed, oops

**Comment by NonhumanFromSteam** [comment]
There are **absolutely** no files in this mod that have anything to do with first person animations so there's no way the recent tf2 update's snap fix is breaking due to this mod; you can even browse the folders of this mod right now and you will see there are no files that change the "models/weapons/c_models/c_CLASS_animations.mdl" or even the "c_CLASS_arms.mdl" files. _( And in the entire history of this mod, these files were never changed or included. )_
It's most likely that another mod you have may be causing it, please be sure this isn't the cause.

**Comment by unsubtract** [comment]
The issue was with a different fix mod designed for viewmodels. Closing
