### ISSUE TITLE
TF2 HHH Burning effect missing

### ISSUE THREAD

**Issue by condor00fr** [agrastiOs/Ultimate-TF2-Visual-Fix-Pack#71]
(Note This fix request was taken from  Valve's official Github and was originaly postedd by user HHHJrr. However I feel like it deserves it's place a lot more here as this awesome pack has the goal of fixing all the visual issues the game currently suffers.

Ever since 2015 October in the Invasion or Scream Fortress update(i only noticed it much later but seems around that time) The Horseless Headless Horsemann Halloween boss lost the purple flame effect on it's body.
HorsemannFlame.

![194727697-be572708-5487-4433-a2ff-b44fcb1300ae](https://user-images.githubusercontent.com/71549583/207826497-80ca2acd-4c5c-4c9e-8e57-fe4c7e9c088d.png)

I didn't see the change mentioned anywhere or anyone noticing the change, but the image above has a clear difference.

**Comment by Whurrhurr** [comment]
i don't think there's anything the UVF pack can do about this, since from what i understand (without looking at the leaked source code, going completely off of assumptions here) the headless_hatman entity no longer has the bits of purple flames around his body anymore. the only way for those to come back is to get someone to submit a "fix" to valve that re-adds the purple flames back to the entity's code.

**Comment by condor00fr** [comment]
Indeed! would be so cool to see it back!

**Comment by Whurrhurr** [comment]
officially fixed by valve in the scream fortress 2023 update.

**Comment by agrastiOs** [comment]
Closing as has been fixed in the official game.
